services:
  app:
    build:
      context: ./app
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy          # wait for postgres to be ready
    env_file:
      - ./app/.env
    ports:
      - 127.0.0.1:31000:8000
    volumes:
      - ./app/:/app

  db:
    image: "postgres:16-alpine"
    restart: "on-failure"
    env_file:
      - ./app/.env
    volumes:
      - ./app/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10
